// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIHWooFWDVKnKPWhpHH2pes1OOfAtuOw',
    appId: '1:639130957255:android:b2b00d0cd1535badac95e2',
    messagingSenderId: '639130957255',
    projectId: 'expenseflow-6e122',
    storageBucket: 'expenseflow-6e122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5kzXLbZgObLhigxQ4BBMfZOB3EIIH5-M',
    appId: '1:639130957255:ios:f6a1e115e4e7ece3ac95e2',
    messagingSenderId: '639130957255',
    projectId: 'expenseflow-6e122',
    storageBucket: 'expenseflow-6e122.firebasestorage.app',
    androidClientId: '639130957255-2aiddobofb1p31atggi46e7e9j5o57f6.apps.googleusercontent.com',
    iosClientId: '639130957255-1lolsea3la7ohdjfsv1n5eu2tkadpjqh.apps.googleusercontent.com',
    iosBundleId: 'com.gabbar.expenseflow',
  );

}